spring:
  application:
    name: Blog

  datasource:
    url: jdbc:mysql://192.168.17.128:3306/blog
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: user
      password: 1234

  data:
    redis:
      url: redis://192.168.17.128:6379
      port: 6379

  mail:
    ssl:
      enabled: true
    port:

server:
  port: 8080
  address: 0.0.0.0

mybatis:
  type-aliases-package: org.naer.blog.Mapper.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  charset:
    file: utf-8
    console: UTF-8
