name: Node.js CI for Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./client

    - name: Run linting checks
      run: npm run lint
      working-directory: ./client

    - name: Build the project
      run: npm run build
      working-directory: ./client

    - name: Run unit tests
      run: npm run test:unit
      working-directory: ./client
